version: '3'
services:
  app:
    image: f1rq/website
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    environment:
      - PORT=80

